spring.application.name=foodiesapi

#mongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URL}

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
asw.secret.key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucketname=${AWS_BUCKET_NAME}

jwt.secret.key=${JWT_SECRET_KEY}

#RAZORPAY CONFIGURATION
razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}

server.port=${PORT:8080}


